schema_version = "1.0.0"

id = "list_blender_extensions"
version = "1.0.0"
name = "List Blender Extensions"
tagline = "Generate a list of installed blender extensions"
maintainer = "Wooniety"
type = "add-on"
website = "https://github.com/Wooniety/List-Blender-Extensions"
tags = ["System", "Import-Export"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Export the extension list to disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/.git*",
  "/.venv/",
]